---
title: "Chapter 5 Exercises"
date: "`r Sys.Date()`"
author: "Jumping Rivers"
output: html_vignette
---
<!--
%\VignetteEngine{knitr::rmarkdown}
%\VignetteIndexEntry{Chapter 5 Exercises}
-->

## Exercise 18: interactive graphics

  * Open `chapter5/interactive1.R` and run.
    * Using `textOutput()` and `input$click`, get the shiny app to print out the `x` and `y` coordinates of a user's click on the plot
    * Change the output to display `x` and `y` to 4 significant figures.
    * If you are familiar with `ggplot2`, change the base graphic plot to a ggplot2 scatter plot.
    * Change the plot to a boxplot - does it still work?
  * Open `chapter2/interactive2.R` and run. Explore the other types of point selection.

## Exercise 19: acting on interactive graphics

  * Open `chapter5/interactive3.R` and run.
  * In the `nearPoints` function, what does
    * the argument `threshold = 100` do?
    * the argument `maxpoints = 2` do?
    * the argument `allRows = TRUE` do?
    * the argument `addDist = TRUE` do?
* When you click on a point, remove that point from the regression calculation and
    refit the line (this is quite hard!). I did this by using the `allRows = TRUE` argument.
    * Add a reset button to your app
    * Rather than clicking on a point, try brushing. See `brushedPoints()` for this.

## Exercise 20: invalidating reactive contexts

  * Open `chapter5/invalidate.R` and run.
  * Can you change the app such that it produces a plot of movie ratings vs durations from a random sample of movies that changes every 5 seconds
  * Create a summary output of movie years, let this be it's own reactive context updating every 3 seconds from a random sample of movies.
  * __Hard:__ Create a summary output of movie years, let this be it's own reactive context updating every 3 seconds by cycling through the movie genres.


This is a less guided exercise. The file below will give you some example code that you can play around with and modify to see what is going on. Feel free to try things with your own data.

## Exercise 21: Dynamic user interfaces

  * Open `chapter5/ui_app1` and run
  