---
title: "Chapter 1 Exercises"
author: "Jumping Rivers"
output: html_vignette
---
<!--
%\VignetteEngine{knitr::rmarkdown}
%\VignetteIndexEntry{Chapter 1 Exercises}
-->

```{r echo=FALSE, message=FALSE}
library("jrShiny")
library("shiny")
```

## Exercise 1 (5 minutes)


  * In RStudio, select `File`, then `New Project`. Create a new RStudio project in 
  an empty directory. Call it something useful like `shiny_day1_practice`.
  * In Rstudio, select `File`, then `New File`, then `R markdown...`.
  * Select shiny from the options on the left
  * Give an appropriate title, such as `my first app`
  * Once you have created the document, delete line 7 onwards and save the document.
  * Congrats, you've created your first (albeit empty) shiny app.
  
## Exercise 2 (5 minutes)

  * Add a code chunk that contains the simple code `1 + 1`
  * Make the chunk display but not run the code, then knit the document
  * Make the chunk run but not display the code, then knit the document
  
## Exercise 3 (10 minutes)

Add the following widgets to your R markdown document, the options for each widget can be whatever you like at this stage:

  * `selectInput()` 
  * `sliderInput()` 
  * `numericInput()` 
  * `radioButtons()`, see `?radioButtons` for help
  

## Exercise 4 (10 minutes)

  * Run the command `jrShiny::create_project()`. This should create two directories: `original` and `exercises`.
  * Open `exercises/chapter1/exercise4.Rmd` and run the script. 
  * Display the chosen number on the slider using a `renderText()`
  * To simulate random numbers we could use the code `runif(n = input$n)`, display a plot of the random numbers using `renderPlot()`
  
## Exercise 5 (10 minutes)

`iris` is an infamous dataset within the programming community. It contains widght and length measurements for the `sepal` and `petal` of three different flowers.

  * Open `chapter1/exercise5.Rmd` and run. 
  * What is `choices = unique(iris$Species)` doing?
  * We can filter the `iris` data frame for the user's chosen species with the code `selected = iris[iris$Species == input$flower_choice,]`
      * Use `renderText()` to add text that displays the average petal length for the species chosen by the user.
      * (Harder) Display a plot of `Petal.Width` v `Petal.Length` for the species chosen by the user.