---
title: "svgPanZoom"
date: "`r Sys.Date()`"
author: "Jumping Rivers"
output: html_vignette
---
  
<!--
%\VignetteEngine{knitr::rmarkdown}
%\VignetteIndexEntry{svgPanZoom}
-->
  
## Overview

This package allows us to add panning and zooming to any R graphics, e.g. base, ggplot2, lattice.
To install t
```{r eval=FALSE}
install.packages("svgPanZoom")
install.packages("svglite") # Needed for base
```
To install the development version use
```{r eval=FALSE}
devtools::install_github("timelyportfolio/svgPanZoom")
```

## Examples

Load the package in the usual way
```{r message=FALSE}
library("svgPanZoom") 
library("svglite")## For base
```
Then just wrap a base graphic function call
```{r, message=FALSE}
svgPanZoom(
  svglite:::inlineSVG(
    plot(1:10)
  ),controlIconsEnabled=TRUE
)
```
`ggplot2` is just as easy
```{r, message=FALSE}
library("ggplot2")
data(mtcars, package="datasets")
#install.packages("gridSVG")
d = ggplot(mtcars, aes(mpg, disp, colour=disp)) + geom_jitter() + 
  theme_bw()
svgPanZoom(d, controlIconsEnabled = TRUE)
```

#### Links

  * [CRAN](https://cran.rstudio.com/web/packages/svgPanZoom/)
  * [github](https://github.com/timelyportfolio/svgPanZoom)
  * [Examples](http://www.buildingwidgets.com/blog/2015/1/15/week-02-)